# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23bc1312e18d5b1ea73d86693320081301489d13e8e4285a4974248dbd48f0c0cadacb769829ca09d349bfb5c522435901d6d3a8fec20fd0e7b2d090cfa45450

test:
  secret_key_base: fdf8771401bcdb2e31c05b40056ca13a80bc98d20c29d73ae7ae19c1577da8d0ae26b60df94c47891582c1541dabd9dfa13b842cfc63c78b42359e1d2d0970f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
